# Generated by Django 4.2.5 on 2023-11-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrosonar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('sensor_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hydrosonar.sensordata')),
                ('volume_litros', models.FloatField()),
                ('porcentagem_agua', models.FloatField()),
                ('valvula_ativa', models.BooleanField()),
            ],
        ),
    ]
